### ISSUE TITLE
Suggestion: upload image using HTTPS

### ISSUE THREAD

**Issue by 9Morello** [Kamiyaa/ruiji#1]
I think the title says it all. Currently, its using port 80 to upload the images.
Great work!

**Comment by kamiyaa** [comment]
I'm not really sure how to verify it is using port 443 instead of port 80. But I guess I'll close this issue as you committed with HTTPS support. :)

**Comment by 9Morello** [comment]
@Kamiyaa Thanks for the fast reply. I was using TCPBlock on OS X to monitor traffic and saw the port 80 connection attempt.
